org.gradle.jvmargs=-Xmx1G
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=10808
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=10808
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.18.4
mod_version=1.0
maven_group=com.lirxowo
archives_base_name=itemglow
fabric_version=0.116.9+1.21.1
